almost done with doubley linked list. need to fight with compiler
```
error[E0594]: cannot assign to data in an `Rc`
  --> src\main.rs:82:7
   |
82 |       new_tail.next = None;
   |       ^^^^^^^^^^^^^ cannot assign
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<Node>`

error[E0594]: cannot assign to data in an `Rc`
  --> src\main.rs:87:5
   |
87 |     old_tail.prev = None;
   |     ^^^^^^^^^^^^^ cannot assign
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<Node>`

error[E0594]: cannot assign to data in an `Rc`
  --> src\main.rs:88:5
   |
88 |     old_tail.next = None;
   |     ^^^^^^^^^^^^^ cannot assign
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<Node>`

error: aborting due to 19 previous errors
```